project_name: changecase
builds:
  - main: .
    id: "lower"
    dir: "./cmd/lower"
    binary: lower
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
      - windows
      - freebsd
    goarch:
      - amd64
      - arm
      - arm64
      - mips
    goarm:
      - 7
    ignore:
      - goos: freebsd
        goarch: arm
      - goos: freebsd
        goarch: arm64
      - goos: freebsd
        goarch: mips
      - goos: windows
        goarch: arm
        goarm: 7
      - goos: windows
        goarch: arm64
      - goos: linux
        goarch: arm64

  - main: .
    id: "upper"
    dir: "./cmd/upper"
    binary: upper
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
      - windows
      - freebsd
    goarch:
      - amd64
      - arm
      - arm64
      - mips
    goarm:
      - 7
    ignore:
      - goos: freebsd
        goarch: arm
      - goos: freebsd
        goarch: arm64
      - goos: freebsd
        goarch: mips
      - goos: windows
        goarch: arm
        goarm: 7
      - goos: windows
        goarch: arm64
      - goos: linux
        goarch: arm64

  - main: .
    id: "titlecase"
    dir: "./cmd/titlecase"
    binary: titlecase
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
      - windows
      - freebsd
    goarch:
      - amd64
      - arm
      - arm64
      - mips
    goarm:
      - 7
    ignore:
      - goos: freebsd
        goarch: arm
      - goos: freebsd
        goarch: arm64
      - goos: freebsd
        goarch: mips
      - goos: windows
        goarch: arm
        goarm: 7
      - goos: windows
        goarch: arm64
      - goos: linux
        goarch: arm64

archives:
  - name_template: >-
      {{- .ProjectName }}_
      {{- .Version }}_
      {{- if eq .Os "darwin" }}macos
      {{- else }}{{ .Os}}{{ end }}_
      {{- .Arch }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    format: tar.xz
    format_overrides:
      - goos: windows
        format: zip
    wrap_in_directory: true
checksum:
  name_template: "{{ .ProjectName }}_{{ .Version }}--sha256_checksums.txt"
release:
  draft: true
